### ISSUE TITLE
Support node 20.x

### ISSUE THREAD

**Issue by leoVVei** [DataDog/datadog-cloudformation-macro#110]
I want macro to support node version 20.x

https://github.com/DataDog/datadog-cloudformation-macro/blob/48e7758961c22756f7ca22c41dea87c4b9d4ae3c/serverless/src/layer.ts#L59

**Comment by vieirai** [comment]
Hi @duncanista I can see the PR was merged, the but there hasn't been a release for this yet?
https://github.com/DataDog/datadog-cloudformation-macro/releases

**Comment by astuyve** [comment]
Hey folks, I just shipped 0.9.0 and this should be released.

Let me know if you have any questions!
