### ISSUE TITLE
End of support for Node.js v16.x

### ISSUE THREAD

**Issue by Omar-Bishtawi** [DataDog/datadog-cloudformation-macro#120]
## Expected Behavior

Use latest LTS Node version supported by aws (Node 20.x)

## Actual Behavior
Node16.x which is being used by this macro function will soon be deprecated ([Jun 12, 2024](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)) . 
will there be any issue if Node20.X is used instead ?

it's simmilar change to this issue https://github.com/DataDog/datadog-cloudformation-macro/issues/71

**Comment by gustavodaltoe** [comment]
I see that @duncanista PR's is merged to update node to 20.x, but when I download the `https://datadog-cloudformation-template.s3.amazonaws.com/aws/serverless-macro/latest.yml` file, I still see that the runtime is `nodejs16.x`.
I'm trying to update my lambdas to `node20.x` runtime and noticed that datadog is failing with `No Lambda layer available for runtime: nodejs20.x`

**Comment by astuyve** [comment]
Hey @gustavodaltoe we need to revert this as govcloud doesn't yet support node20.

We'll go to node18 for now.
