### ISSUE TITLE
Docs are ahead of the release

### ISSUE THREAD

**Issue by inhumantsar** [DataDog/datadog-cloudformation-macro#53]
Looks like yesterday's merge adding Secrets Manager support is already in the public docs but is not yet released: https://docs.datadoghq.com/serverless/libraries_integrations/macro/#configuration

Let's get that release out! I'm very excited to use it :)

## Expected Behavior

Setting `apiKeySecretArn` would result in no errors.

## Actual Behavior

DatadogServerless failed with: When `extensionLayerVersion` is set, `apiKey` or `apiKmsKey` must also be set.

## Steps to Reproduce the Problem

  1. Set `apiKeySecretArn` in the DatadogServerless layer config
  1. `sam deploy`

## Specifications

  For the Datadog Serverless Macro:
  - Deployment method and version (CloudFormation, SAM, CDK):  CloudFormation
  - Datadog CloudFormation Macro version: 0.2.3
  - Lambda function runtime (Python 3.7, Node 10, etc.):

**Comment by duncanista** [comment]
Hey @inhumantsar, sorry for the trouble.
I'm now removing the feature from the docs, should be ready to go once we release the new version of the macro.

**Comment by inhumantsar** [comment]
😭 any idea when that release will be happening? i'm building out some boilerplate for a suite of new projects and would *really* like to use this, but if it's not going to be available soon then i'm going to have to rework things.

**Comment by hghotra** [comment]
Hey @inhumantsar, we'll make a release today within the next hour so you should be able to use it :)

**Comment by duncanista** [comment]
Hey @inhumantsar, we just released version [0.2.4](https://github.com/DataDog/datadog-cloudformation-macro/releases/tag/serverless-macro-0.2.4).
Thank you for opening the issue.

**Comment by inhumantsar** [comment]
![🎉 ](https://cultofthepartyparrot.com/assets/sirocco.gif)
