### ISSUE TITLE
Accessing datadog-cloudformation-template.s3.amazonaws.com/aws/serverless-macro/latest.yml errors with 'Access Denied'

### ISSUE THREAD

**Issue by red632nm** [DataDog/datadog-cloudformation-macro#6]
## Expected Behavior
I was trying to deploy the CloudFormation template.

## Actual Behavior
It fails with: An error occurred (ValidationError) when calling the CreateStack operation: S3 error: Access Denied

## Steps to Reproduce the Problem

  1. run `aws cloudformation create-stack \
  --stack-name datadog-serverless-macro \
  --template-url https://datadog-cloudformation-template.s3.amazonaws.com/aws/serverless-macro/latest.yml \
  --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM`
  
## Specifications

  For the Datadog Serverless Macro:
  - Deployment method and version (CloudFormation, SAM, CDK): 
  - Datadog CloudFormation Macro version: 
  - Lambda function runtime (Python 3.7, Node 10, etc.): 
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by hannah-sun** [comment]
Hi @red632nm, thanks for opening the issue! We've made a fix for the permission issue now. Let us know if this solves the problem for you!

**Comment by red632nm** [comment]
I'm able to deploy, Thanks.
