### ISSUE TITLE
End of support for Node.js v12.x

### ISSUE THREAD

**Issue by fdaciuk** [DataDog/datadog-cloudformation-macro#71]
## Expected Behavior
The template should create a lambda with Node.js runtime in a LTS version.

## Actual Behavior
The lambda is being created with Node.js v12.x.

AWS will end support for Node.js v12.x runtime in November 1, 2022:
https://aws.amazon.com/pt/blogs/developer/announcing-the-end-of-support-for-node-js-12-x-in-the-aws-sdk-for-javascript-v3/

Is there any problem to update the `template.yml` and use v16.x instead of v12.x?

**Comment by astuyve** [comment]
Nope, no problem.
