### ISSUE TITLE
DD_LAMBDA_HANDLER value is set incorrectly after sam deploy

### ISSUE THREAD

**Issue by darin-holloway** [DataDog/datadog-cloudformation-macro#73]
## Expected Behavior
DD_LAMBDA_HANDLER value matches what is in our template.yaml

## Actual Behavior
DD_LAMBDA_HANDLER is set to datadog_lambda.handler.handler, causing the lambda to not run due to a cyclical dependency

## Steps to Reproduce the Problem

  1. Add DatadogServerless transform to your template.yaml       pythonLayerVersion: 62       extensionLayerVersion: 28
  2. Set DD_LAMBDA_HANDER to our app's app.lambda_handler
  3. Set Handler for lambda to datadog_lambda.handler.handler
  4. sam deploy
  5. observe that the value for DD_LAMBDA_HANDLER is incorrect leading to invocation errors

## Specifications

  For the Datadog Serverless Macro:
  - Deployment method and version (CloudFormation, SAM, CDK):  SAM
  - Datadog CloudFormation Macro version:  v0.4.1
  - Lambda function runtime (Python 3.7, Node 10, etc.):   python 3.9
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by darin-holloway** [comment]
behavior was also observed with a nodejs 16 application

**Comment by tianchu** [comment]
I believe the macro automatically update the handler and DD_LAMBDA_HANDLER env var. So steps 2 & 3 in your reproduction steps are unnecessary. Could that be the cause of the issue?

**Comment by tianchu** [comment]
https://docs.datadoghq.com/serverless/installation/python?tab=awssam has the step by step instructions in case it's helpful.

**Comment by darin-holloway** [comment]
@tianchu thank you, going to test with DD_LAMBDA_HANDLER unset to confirm if the transform does to job for us

**Comment by darin-holloway** [comment]
Confirmed working correctly now, thanks for the tip
